version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key_here
      - DB_NAME=employee_db
      - DB_USER=employee_user
      - DB_PASSWORD=employee_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
