# Generated by Django 5.2.5 on 2025-08-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
